language: python

python:
  - 2.6
  - 2.7

env:
  - NET_SNMP_VERSION=5.7.2
  - NET_SNMP_VERSION=5.7.3

before_install:
  # Install build dependencies
  - sudo apt-get update
  - sudo apt-get install -y autoconf libtool make libperl-dev python-dev

  # Download and extract the required version of Net-SNMP
  - wget http://downloads.sourceforge.net/sourceforge/net-snmp/net-snmp-$NET_SNMP_VERSION.tar.gz
  - tar zxvf net-snmp-$NET_SNMP_VERSION.tar.gz
  - cd net-snmp-$NET_SNMP_VERSION

  # Build and install Net-SNMP
  - autoreconf -f -i
  - ./configure
    --prefix=/usr/local
    --enable-ucd-snmp-compatibility
    --enable-ipv6
    --with-default-snmp-version="3"
    --with-sys-contact="root@localhost"
    --with-sys-location="Unknown"
    --with-logfile="/var/log/snmpd.log"
    --with-mib-modules="host misc/ipfwacc ucd-snmp/diskio tunnel ucd-snmp/dlmod"
    --with-persistent-directory="/var/net-snmp"
  - make -j4 NETSNMP_DONT_CHECK_VERSION=1
  - sudo make install
  - sudo ldconfig
  - cd ..

  # Clean up the extracted files
  - rm -rf net-snmp-$NET_SNMP_VERSION

  # Display the build version of Net-SNMP
  - net-snmp-config --version

  # Install the SNMP MIBs
  - sudo apt-get install -y snmp-mibs-downloader

  # Copy our test SNMP config and start up SNMPD
  - sudo cp tests/snmpd.conf /usr/local/etc
  - sudo /usr/local/sbin/snmpd -c /usr/local/etc/snmpd.conf

install:
  # Install all test requirements
  - pip install -r requirements.txt

  # Build the PyNetSNMP C library and copy it to our library for testing
  - python setup.py build
  - cp build/lib.*/pynetsnmp/*.so pynetsnmp/

script:
  - py.test
